name: lnlambda
description: Minimal interface to run lnlambda function with dart.
version: 0.0.1
homepage: https://github.com/dart-lightning/lndart.clightning

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  cln_common: ^0.0.1
  http: ^0.13.4
  json_annotation: ^4.5.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.0.0
  json_serializable: ^6.2.0
  clightning_rpc: ^0.0.1

dependency_overrides:
  cln_common:
    path: ../cln_common
  clightning_rpc:
    path: ../rpc
