name: cln_plugin
description: Dart package that provides an easy and comprehensive interface to develop custom plugins for core lightning in the Dart programming environment.
version: 0.0.1-beta.1
homepage: https://github.com/dart-lightning/lndart.clightning

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  json_annotation: ^4.5.0
  cln_common: ^0.0.1-beta.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.0.0
  json_serializable: ^6.2.0
  clightning_rpc: ^0.0.2-beta.1

# dependency_overrides:
#  cln_common:
#    path: ../cln_common
#  clightning_rpc:
#    path: ../rpc
