name: clightning_rpc
description: Dart framework for C-Lightning to work with the RPC interface.
version: 0.0.1
homepage: https://github.com/dart-lightning/clightning-rpc.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0

dependencies:
  json_rpc_2: ^3.0.1
  jsonrpc2: ^3.0.1
  logger: ^1.0.0
  cln_common:
    path: ../cln_common